import { CountryModel } from '../models/Country';

// Comprehensive list of countries with ISO codes
// This is a seed data file - in production, you might load from a JSON file
const COUNTRIES = [
  { iso_code: 'US', iso_code_3: 'USA', name: 'United States', region: 'Americas' },
  { iso_code: 'GB', iso_code_3: 'GBR', name: 'United Kingdom', region: 'Europe' },
  { iso_code: 'CA', iso_code_3: 'CAN', name: 'Canada', region: 'Americas' },
  { iso_code: 'AU', iso_code_3: 'AUS', name: 'Australia', region: 'Oceania' },
  { iso_code: 'DE', iso_code_3: 'DEU', name: 'Germany', region: 'Europe' },
  { iso_code: 'FR', iso_code_3: 'FRA', name: 'France', region: 'Europe' },
  { iso_code: 'IT', iso_code_3: 'ITA', name: 'Italy', region: 'Europe' },
  { iso_code: 'ES', iso_code_3: 'ESP', name: 'Spain', region: 'Europe' },
  { iso_code: 'NL', iso_code_3: 'NLD', name: 'Netherlands', region: 'Europe' },
  { iso_code: 'BE', iso_code_3: 'BEL', name: 'Belgium', region: 'Europe' },
  { iso_code: 'CH', iso_code_3: 'CHE', name: 'Switzerland', region: 'Europe' },
  { iso_code: 'AT', iso_code_3: 'AUT', name: 'Austria', region: 'Europe' },
  { iso_code: 'SE', iso_code_3: 'SWE', name: 'Sweden', region: 'Europe' },
  { iso_code: 'NO', iso_code_3: 'NOR', name: 'Norway', region: 'Europe' },
  { iso_code: 'DK', iso_code_3: 'DNK', name: 'Denmark', region: 'Europe' },
  { iso_code: 'FI', iso_code_3: 'FIN', name: 'Finland', region: 'Europe' },
  { iso_code: 'PL', iso_code_3: 'POL', name: 'Poland', region: 'Europe' },
  { iso_code: 'CZ', iso_code_3: 'CZE', name: 'Czech Republic', region: 'Europe' },
  { iso_code: 'GR', iso_code_3: 'GRC', name: 'Greece', region: 'Europe' },
  { iso_code: 'PT', iso_code_3: 'PRT', name: 'Portugal', region: 'Europe' },
  { iso_code: 'IE', iso_code_3: 'IRL', name: 'Ireland', region: 'Europe' },
  { iso_code: 'JP', iso_code_3: 'JPN', name: 'Japan', region: 'Asia' },
  { iso_code: 'CN', iso_code_3: 'CHN', name: 'China', region: 'Asia' },
  { iso_code: 'IN', iso_code_3: 'IND', name: 'India', region: 'Asia' },
  { iso_code: 'KR', iso_code_3: 'KOR', name: 'South Korea', region: 'Asia' },
  { iso_code: 'SG', iso_code_3: 'SGP', name: 'Singapore', region: 'Asia' },
  { iso_code: 'MY', iso_code_3: 'MYS', name: 'Malaysia', region: 'Asia' },
  { iso_code: 'TH', iso_code_3: 'THA', name: 'Thailand', region: 'Asia' },
  { iso_code: 'ID', iso_code_3: 'IDN', name: 'Indonesia', region: 'Asia' },
  { iso_code: 'PH', iso_code_3: 'PHL', name: 'Philippines', region: 'Asia' },
  { iso_code: 'VN', iso_code_3: 'VNM', name: 'Vietnam', region: 'Asia' },
  { iso_code: 'BR', iso_code_3: 'BRA', name: 'Brazil', region: 'Americas' },
  { iso_code: 'MX', iso_code_3: 'MEX', name: 'Mexico', region: 'Americas' },
  { iso_code: 'AR', iso_code_3: 'ARG', name: 'Argentina', region: 'Americas' },
  { iso_code: 'CL', iso_code_3: 'CHL', name: 'Chile', region: 'Americas' },
  { iso_code: 'CO', iso_code_3: 'COL', name: 'Colombia', region: 'Americas' },
  { iso_code: 'PE', iso_code_3: 'PER', name: 'Peru', region: 'Americas' },
  { iso_code: 'ZA', iso_code_3: 'ZAF', name: 'South Africa', region: 'Africa' },
  { iso_code: 'EG', iso_code_3: 'EGY', name: 'Egypt', region: 'Africa' },
  { iso_code: 'NG', iso_code_3: 'NGA', name: 'Nigeria', region: 'Africa' },
  { iso_code: 'KE', iso_code_3: 'KEN', name: 'Kenya', region: 'Africa' },
  { iso_code: 'TR', iso_code_3: 'TUR', name: 'Turkey', region: 'Asia' },
  { iso_code: 'RU', iso_code_3: 'RUS', name: 'Russia', region: 'Europe' },
  { iso_code: 'SA', iso_code_3: 'SAU', name: 'Saudi Arabia', region: 'Asia' },
  { iso_code: 'AE', iso_code_3: 'ARE', name: 'United Arab Emirates', region: 'Asia' },
  { iso_code: 'IL', iso_code_3: 'ISR', name: 'Israel', region: 'Asia' },
  { iso_code: 'NZ', iso_code_3: 'NZL', name: 'New Zealand', region: 'Oceania' },
  { iso_code: 'HU', iso_code_3: 'HUN', name: 'Hungary', region: 'Europe' },
  { iso_code: 'RO', iso_code_3: 'ROU', name: 'Romania', region: 'Europe' },
  { iso_code: 'BG', iso_code_3: 'BGR', name: 'Bulgaria', region: 'Europe' },
  { iso_code: 'HR', iso_code_3: 'HRV', name: 'Croatia', region: 'Europe' },
  { iso_code: 'RS', iso_code_3: 'SRB', name: 'Serbia', region: 'Europe' },
  { iso_code: 'UA', iso_code_3: 'UKR', name: 'Ukraine', region: 'Europe' },
  { iso_code: 'BY', iso_code_3: 'BLR', name: 'Belarus', region: 'Europe' },
  { iso_code: 'PK', iso_code_3: 'PAK', name: 'Pakistan', region: 'Asia' },
  { iso_code: 'BD', iso_code_3: 'BGD', name: 'Bangladesh', region: 'Asia' },
  { iso_code: 'LK', iso_code_3: 'LKA', name: 'Sri Lanka', region: 'Asia' },
  { iso_code: 'IQ', iso_code_3: 'IRQ', name: 'Iraq', region: 'Asia' },
  { iso_code: 'IR', iso_code_3: 'IRN', name: 'Iran', region: 'Asia' },
  { iso_code: 'AF', iso_code_3: 'AFG', name: 'Afghanistan', region: 'Asia' },
  { iso_code: 'KZ', iso_code_3: 'KAZ', name: 'Kazakhstan', region: 'Asia' },
  { iso_code: 'UZ', iso_code_3: 'UZB', name: 'Uzbekistan', region: 'Asia' },
  { iso_code: 'MN', iso_code_3: 'MNG', name: 'Mongolia', region: 'Asia' },
  { iso_code: 'TW', iso_code_3: 'TWN', name: 'Taiwan', region: 'Asia' },
  { iso_code: 'HK', iso_code_3: 'HKG', name: 'Hong Kong', region: 'Asia' },
  { iso_code: 'GH', iso_code_3: 'GHA', name: 'Ghana', region: 'Africa' },
  { iso_code: 'TZ', iso_code_3: 'TZA', name: 'Tanzania', region: 'Africa' },
  { iso_code: 'UG', iso_code_3: 'UGA', name: 'Uganda', region: 'Africa' },
  { iso_code: 'ET', iso_code_3: 'ETH', name: 'Ethiopia', region: 'Africa' },
  { iso_code: 'MA', iso_code_3: 'MAR', name: 'Morocco', region: 'Africa' },
  { iso_code: 'DZ', iso_code_3: 'DZA', name: 'Algeria', region: 'Africa' },
  { iso_code: 'TN', iso_code_3: 'TUN', name: 'Tunisia', region: 'Africa' },
  { iso_code: 'LY', iso_code_3: 'LBY', name: 'Libya', region: 'Africa' },
  { iso_code: 'SD', iso_code_3: 'SDN', name: 'Sudan', region: 'Africa' },
  { iso_code: 'AO', iso_code_3: 'AGO', name: 'Angola', region: 'Africa' },
  { iso_code: 'MZ', iso_code_3: 'MOZ', name: 'Mozambique', region: 'Africa' },
  { iso_code: 'ZM', iso_code_3: 'ZMB', name: 'Zambia', region: 'Africa' },
  { iso_code: 'ZW', iso_code_3: 'ZWE', name: 'Zimbabwe', region: 'Africa' },
  { iso_code: 'BW', iso_code_3: 'BWA', name: 'Botswana', region: 'Africa' },
  { iso_code: 'NA', iso_code_3: 'NAM', name: 'Namibia', region: 'Africa' },
  { iso_code: 'SN', iso_code_3: 'SEN', name: 'Senegal', region: 'Africa' },
  { iso_code: 'CI', iso_code_3: 'CIV', name: 'Ivory Coast', region: 'Africa' },
  { iso_code: 'CM', iso_code_3: 'CMR', name: 'Cameroon', region: 'Africa' },
  { iso_code: 'CG', iso_code_3: 'COG', name: 'Congo', region: 'Africa' },
  { iso_code: 'CD', iso_code_3: 'COD', name: 'DR Congo', region: 'Africa' },
  { iso_code: 'GA', iso_code_3: 'GAB', name: 'Gabon', region: 'Africa' },
  { iso_code: 'GN', iso_code_3: 'GIN', name: 'Guinea', region: 'Africa' },
  { iso_code: 'ML', iso_code_3: 'MLI', name: 'Mali', region: 'Africa' },
  { iso_code: 'BF', iso_code_3: 'BFA', name: 'Burkina Faso', region: 'Africa' },
  { iso_code: 'NE', iso_code_3: 'NER', name: 'Niger', region: 'Africa' },
  { iso_code: 'TD', iso_code_3: 'TCD', name: 'Chad', region: 'Africa' },
  { iso_code: 'MR', iso_code_3: 'MRT', name: 'Mauritania', region: 'Africa' },
  { iso_code: 'BJ', iso_code_3: 'BEN', name: 'Benin', region: 'Africa' },
  { iso_code: 'TG', iso_code_3: 'TGO', name: 'Togo', region: 'Africa' },
  { iso_code: 'SL', iso_code_3: 'SLE', name: 'Sierra Leone', region: 'Africa' },
  { iso_code: 'LR', iso_code_3: 'LBR', name: 'Liberia', region: 'Africa' },
  { iso_code: 'GM', iso_code_3: 'GMB', name: 'Gambia', region: 'Africa' },
  { iso_code: 'GW', iso_code_3: 'GNB', name: 'Guinea-Bissau', region: 'Africa' },
  { iso_code: 'CV', iso_code_3: 'CPV', name: 'Cape Verde', region: 'Africa' },
  { iso_code: 'ST', iso_code_3: 'STP', name: 'São Tomé and Príncipe', region: 'Africa' },
  { iso_code: 'GQ', iso_code_3: 'GNQ', name: 'Equatorial Guinea', region: 'Africa' },
  { iso_code: 'CF', iso_code_3: 'CAF', name: 'Central African Republic', region: 'Africa' },
  { iso_code: 'RW', iso_code_3: 'RWA', name: 'Rwanda', region: 'Africa' },
  { iso_code: 'BI', iso_code_3: 'BDI', name: 'Burundi', region: 'Africa' },
  { iso_code: 'MW', iso_code_3: 'MWI', name: 'Malawi', region: 'Africa' },
  { iso_code: 'LS', iso_code_3: 'LSO', name: 'Lesotho', region: 'Africa' },
  { iso_code: 'SZ', iso_code_3: 'SWZ', name: 'Eswatini', region: 'Africa' },
  { iso_code: 'MG', iso_code_3: 'MDG', name: 'Madagascar', region: 'Africa' },
  { iso_code: 'MU', iso_code_3: 'MUS', name: 'Mauritius', region: 'Africa' },
  { iso_code: 'SC', iso_code_3: 'SYC', name: 'Seychelles', region: 'Africa' },
  { iso_code: 'KM', iso_code_3: 'COM', name: 'Comoros', region: 'Africa' },
  { iso_code: 'DJ', iso_code_3: 'DJI', name: 'Djibouti', region: 'Africa' },
  { iso_code: 'ER', iso_code_3: 'ERI', name: 'Eritrea', region: 'Africa' },
  { iso_code: 'SO', iso_code_3: 'SOM', name: 'Somalia', region: 'Africa' },
  { iso_code: 'YE', iso_code_3: 'YEM', name: 'Yemen', region: 'Asia' },
  { iso_code: 'OM', iso_code_3: 'OMN', name: 'Oman', region: 'Asia' },
  { iso_code: 'QA', iso_code_3: 'QAT', name: 'Qatar', region: 'Asia' },
  { iso_code: 'BH', iso_code_3: 'BHR', name: 'Bahrain', region: 'Asia' },
  { iso_code: 'KW', iso_code_3: 'KWT', name: 'Kuwait', region: 'Asia' },
  { iso_code: 'JO', iso_code_3: 'JOR', name: 'Jordan', region: 'Asia' },
  { iso_code: 'LB', iso_code_3: 'LBN', name: 'Lebanon', region: 'Asia' },
  { iso_code: 'SY', iso_code_3: 'SYR', name: 'Syria', region: 'Asia' },
  { iso_code: 'PS', iso_code_3: 'PSE', name: 'Palestine', region: 'Asia' },
  { iso_code: 'CY', iso_code_3: 'CYP', name: 'Cyprus', region: 'Europe' },
  { iso_code: 'MT', iso_code_3: 'MLT', name: 'Malta', region: 'Europe' },
  { iso_code: 'IS', iso_code_3: 'ISL', name: 'Iceland', region: 'Europe' },
  { iso_code: 'EE', iso_code_3: 'EST', name: 'Estonia', region: 'Europe' },
  { iso_code: 'LV', iso_code_3: 'LVA', name: 'Latvia', region: 'Europe' },
  { iso_code: 'LT', iso_code_3: 'LTU', name: 'Lithuania', region: 'Europe' },
  { iso_code: 'SK', iso_code_3: 'SVK', name: 'Slovakia', region: 'Europe' },
  { iso_code: 'SI', iso_code_3: 'SVN', name: 'Slovenia', region: 'Europe' },
  { iso_code: 'LU', iso_code_3: 'LUX', name: 'Luxembourg', region: 'Europe' },
  { iso_code: 'MC', iso_code_3: 'MCO', name: 'Monaco', region: 'Europe' },
  { iso_code: 'LI', iso_code_3: 'LIE', name: 'Liechtenstein', region: 'Europe' },
  { iso_code: 'SM', iso_code_3: 'SMR', name: 'San Marino', region: 'Europe' },
  { iso_code: 'VA', iso_code_3: 'VAT', name: 'Vatican City', region: 'Europe' },
  { iso_code: 'AD', iso_code_3: 'AND', name: 'Andorra', region: 'Europe' },
  { iso_code: 'MD', iso_code_3: 'MDA', name: 'Moldova', region: 'Europe' },
  { iso_code: 'GE', iso_code_3: 'GEO', name: 'Georgia', region: 'Asia' },
  { iso_code: 'AM', iso_code_3: 'ARM', name: 'Armenia', region: 'Asia' },
  { iso_code: 'AZ', iso_code_3: 'AZE', name: 'Azerbaijan', region: 'Asia' },
  { iso_code: 'TM', iso_code_3: 'TKM', name: 'Turkmenistan', region: 'Asia' },
  { iso_code: 'TJ', iso_code_3: 'TJK', name: 'Tajikistan', region: 'Asia' },
  { iso_code: 'KG', iso_code_3: 'KGZ', name: 'Kyrgyzstan', region: 'Asia' },
  { iso_code: 'MV', iso_code_3: 'MDV', name: 'Maldives', region: 'Asia' },
  { iso_code: 'BT', iso_code_3: 'BTN', name: 'Bhutan', region: 'Asia' },
  { iso_code: 'NP', iso_code_3: 'NPL', name: 'Nepal', region: 'Asia' },
  { iso_code: 'MM', iso_code_3: 'MMR', name: 'Myanmar', region: 'Asia' },
  { iso_code: 'LA', iso_code_3: 'LAO', name: 'Laos', region: 'Asia' },
  { iso_code: 'KH', iso_code_3: 'KHM', name: 'Cambodia', region: 'Asia' },
  { iso_code: 'BN', iso_code_3: 'BRN', name: 'Brunei', region: 'Asia' },
  { iso_code: 'TL', iso_code_3: 'TLS', name: 'Timor-Leste', region: 'Asia' },
  { iso_code: 'PG', iso_code_3: 'PNG', name: 'Papua New Guinea', region: 'Oceania' },
  { iso_code: 'FJ', iso_code_3: 'FJI', name: 'Fiji', region: 'Oceania' },
  { iso_code: 'SB', iso_code_3: 'SLB', name: 'Solomon Islands', region: 'Oceania' },
  { iso_code: 'VU', iso_code_3: 'VUT', name: 'Vanuatu', region: 'Oceania' },
  { iso_code: 'NC', iso_code_3: 'NCL', name: 'New Caledonia', region: 'Oceania' },
  { iso_code: 'PF', iso_code_3: 'PYF', name: 'French Polynesia', region: 'Oceania' },
  { iso_code: 'WS', iso_code_3: 'WSM', name: 'Samoa', region: 'Oceania' },
  { iso_code: 'TO', iso_code_3: 'TON', name: 'Tonga', region: 'Oceania' },
  { iso_code: 'TV', iso_code_3: 'TUV', name: 'Tuvalu', region: 'Oceania' },
  { iso_code: 'KI', iso_code_3: 'KIR', name: 'Kiribati', region: 'Oceania' },
  { iso_code: 'NR', iso_code_3: 'NRU', name: 'Nauru', region: 'Oceania' },
  { iso_code: 'PW', iso_code_3: 'PLW', name: 'Palau', region: 'Oceania' },
  { iso_code: 'FM', iso_code_3: 'FSM', name: 'Micronesia', region: 'Oceania' },
  { iso_code: 'MH', iso_code_3: 'MHL', name: 'Marshall Islands', region: 'Oceania' },
  { iso_code: 'UY', iso_code_3: 'URY', name: 'Uruguay', region: 'Americas' },
  { iso_code: 'PY', iso_code_3: 'PRY', name: 'Paraguay', region: 'Americas' },
  { iso_code: 'BO', iso_code_3: 'BOL', name: 'Bolivia', region: 'Americas' },
  { iso_code: 'EC', iso_code_3: 'ECU', name: 'Ecuador', region: 'Americas' },
  { iso_code: 'VE', iso_code_3: 'VEN', name: 'Venezuela', region: 'Americas' },
  { iso_code: 'GY', iso_code_3: 'GUY', name: 'Guyana', region: 'Americas' },
  { iso_code: 'SR', iso_code_3: 'SUR', name: 'Suriname', region: 'Americas' },
  { iso_code: 'GF', iso_code_3: 'GUF', name: 'French Guiana', region: 'Americas' },
  { iso_code: 'FK', iso_code_3: 'FLK', name: 'Falkland Islands', region: 'Americas' },
  { iso_code: 'GS', iso_code_3: 'SGS', name: 'South Georgia', region: 'Americas' },
  { iso_code: 'CR', iso_code_3: 'CRI', name: 'Costa Rica', region: 'Americas' },
  { iso_code: 'PA', iso_code_3: 'PAN', name: 'Panama', region: 'Americas' },
  { iso_code: 'NI', iso_code_3: 'NIC', name: 'Nicaragua', region: 'Americas' },
  { iso_code: 'HN', iso_code_3: 'HND', name: 'Honduras', region: 'Americas' },
  { iso_code: 'SV', iso_code_3: 'SLV', name: 'El Salvador', region: 'Americas' },
  { iso_code: 'GT', iso_code_3: 'GTM', name: 'Guatemala', region: 'Americas' },
  { iso_code: 'BZ', iso_code_3: 'BLZ', name: 'Belize', region: 'Americas' },
  { iso_code: 'CU', iso_code_3: 'CUB', name: 'Cuba', region: 'Americas' },
  { iso_code: 'JM', iso_code_3: 'JAM', name: 'Jamaica', region: 'Americas' },
  { iso_code: 'HT', iso_code_3: 'HTI', name: 'Haiti', region: 'Americas' },
  { iso_code: 'DO', iso_code_3: 'DOM', name: 'Dominican Republic', region: 'Americas' },
  { iso_code: 'PR', iso_code_3: 'PRI', name: 'Puerto Rico', region: 'Americas' },
  { iso_code: 'TT', iso_code_3: 'TTO', name: 'Trinidad and Tobago', region: 'Americas' },
  { iso_code: 'BB', iso_code_3: 'BRB', name: 'Barbados', region: 'Americas' },
  { iso_code: 'BS', iso_code_3: 'BHS', name: 'Bahamas', region: 'Americas' },
  { iso_code: 'GD', iso_code_3: 'GRD', name: 'Grenada', region: 'Americas' },
  { iso_code: 'LC', iso_code_3: 'LCA', name: 'Saint Lucia', region: 'Americas' },
  { iso_code: 'VC', iso_code_3: 'VCT', name: 'Saint Vincent', region: 'Americas' },
  { iso_code: 'AG', iso_code_3: 'ATG', name: 'Antigua and Barbuda', region: 'Americas' },
  { iso_code: 'DM', iso_code_3: 'DMA', name: 'Dominica', region: 'Americas' },
  { iso_code: 'KN', iso_code_3: 'KNA', name: 'Saint Kitts and Nevis', region: 'Americas' },
  { iso_code: 'MS', iso_code_3: 'MSR', name: 'Montserrat', region: 'Americas' },
  { iso_code: 'VG', iso_code_3: 'VGB', name: 'British Virgin Islands', region: 'Americas' },
  { iso_code: 'VI', iso_code_3: 'VIR', name: 'US Virgin Islands', region: 'Americas' },
  { iso_code: 'AI', iso_code_3: 'AIA', name: 'Anguilla', region: 'Americas' },
  { iso_code: 'BM', iso_code_3: 'BMU', name: 'Bermuda', region: 'Americas' },
  { iso_code: 'KY', iso_code_3: 'CYM', name: 'Cayman Islands', region: 'Americas' },
  { iso_code: 'TC', iso_code_3: 'TCA', name: 'Turks and Caicos', region: 'Americas' },
  { iso_code: 'AW', iso_code_3: 'ABW', name: 'Aruba', region: 'Americas' },
  { iso_code: 'CW', iso_code_3: 'CUW', name: 'Curaçao', region: 'Americas' },
  { iso_code: 'SX', iso_code_3: 'SXM', name: 'Sint Maarten', region: 'Americas' },
  { iso_code: 'BQ', iso_code_3: 'BES', name: 'Caribbean Netherlands', region: 'Americas' },
  { iso_code: 'GL', iso_code_3: 'GRL', name: 'Greenland', region: 'Americas' },
  { iso_code: 'PM', iso_code_3: 'SPM', name: 'Saint Pierre and Miquelon', region: 'Americas' },
  { iso_code: 'BL', iso_code_3: 'BLM', name: 'Saint Barthélemy', region: 'Americas' },
  { iso_code: 'MF', iso_code_3: 'MAF', name: 'Saint Martin', region: 'Americas' },
  { iso_code: 'GP', iso_code_3: 'GLP', name: 'Guadeloupe', region: 'Americas' },
  { iso_code: 'MQ', iso_code_3: 'MTQ', name: 'Martinique', region: 'Americas' },
];

export function seedCountries(): void {
  console.log('Seeding countries...');
  CountryModel.bulkCreate(COUNTRIES);
  console.log(`Seeded ${COUNTRIES.length} countries`);
}

